### ISSUE TITLE
Form for gratitude-input

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-user-stories#1]
## Value Proposition

**As a** user aka gratitude seeker
**I need** a form
**to be able to** write what I am grateful for today.

## Description
<img width="200px" alt="MVP form" src="https://user-images.githubusercontent.com/106114808/179232317-f027b8b2-4b1b-40e3-94e6-7707a376c52f.png">

## Acceptance Criteria

- [ ] There is a headline question called "Wofür bist du heute dankbar?"
- [ ] There is free space (framed box) to introduce you to write your thoughts
- [ ] There is a placeholder text called "Hier ist Platz für die guten Dinge, die heute passiert sind" to stimulate the users thoughts
- [ ] There is a button to switch to the second (2/2) main page of the gratitude app

## Tasks

(for developers team)

- [ ] Create a form
- [ ] Prepare a heading and placeholder text 
- [ ] Create a button to switch to other main page
- [ ] Create global styles
- [ ] Add to Storybook
- [ ] Write tests
- [ ] Create db.js with input form
- [ ] Add to app

**Comment by PReichetanz** [comment]
Hi Yvonne,

this looks really good! 🎉

As you mentioned, I assume this will be your first story to implement, so let's discuss some ideas: 💬

- Regarding the form: I don't see a submit button nor a label for the input, where do you want to place them?
  - I could imagine that the label is screen reader only because the heading is clear enough about what to do here.
- If this is your first user story, you don't have a second page yet; this means your Link to the main page shouldn't be here.
  - You can display the content if the input - after clicking the submit button - underneath the form.
  - In a following user story, you can add this content to the main page after submit (or whereever you want to display it).
