### ISSUE TITLE
Form(+functionality)

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-user-stories#3]
## Value Proposition

**As a** ...user
**I need** ... a form
**to be able to** ...type my daily messages I am grateful for and to see them in a list combined with the date of input.

## Description
<img width="200" alt="Formfunctionality" src="https://user-images.githubusercontent.com/106114808/181309503-9f54b809-cee7-47dd-a441-d10ffd2895fe.png">

## Acceptance Criteria

- [ ] form element
- [ ] date field with placeholder date
- [ ] text field
- [ ] submit button
- [ ] keypad pops up (later on: color of text, typo can be changed individually)

## Tasks

(for developers team)

- [ ] Create feature branch
- [ ] Write components/form hook 
- [ ] Use Storybook
- [ ] Practice on testing
