### ISSUE TITLE
Top navigation bar for date & calendar on click

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-user-stories#4]
## Value Proposition

**As a** ...user
**I need** ...a top navigation bar
**to be able to** ...see the date of the day and the calendar symbol immediately.

## Description

<img width="200" alt="top nav bar" src="https://user-images.githubusercontent.com/106114808/182438229-c3970108-dd97-489d-939c-af7b36ba9a94.png">

## Acceptance Criteria

- [ ] There has to be a seperate bar to navigate
- [ ] The date of the day has to be shown 
- [ ] There will be a button click for calendar
- [ ] on point: date and calendar symbol

## Tasks

(for developers team)

- [ ] Create feature branch
- [ ] Create component
- [ ] Update components
- [ ] Create styled components
- [ ] Add react router
- [ ] Write tests
- [ ] Storybook
