### ISSUE TITLE
Bottom navigation bar for seperate pages

### ISSUE THREAD

**Issue by yvonneadam** [yvonneadam/capstone-user-stories#5]
## Value Proposition

**As a** ...user
**I need** ...a bottom navigation bar
**to be able to** ...see the different pages by symbol immediately.

## Description
<img width="200" alt="Bildschirmfoto 2022-08-02 um 19 33 32" src="https://user-images.githubusercontent.com/106114808/182439475-6e30eb6c-3443-4c53-b71b-8d5ab46fdf7a.png">

<img width="300" alt="Bildschirmfoto 2022-08-02 um 19 33 37" src="https://user-images.githubusercontent.com/106114808/182439493-18fbfd91-d8cb-45ee-88ce-c4ed7c662ee0.png">

## Acceptance Criteria

- [ ] There has to be a seperate bar to navigate
- [ ] Three or four different symbols 
- [ ] The symbols need to be clear to the user (I haven's decided yet which one)
- [ ] Nav bar needs to be contrasted from the rest of the page

## Tasks

(for developers team)

- [ ] Create feature branch
- [ ] Create component
- [ ] Update components
- [ ] Create styled components
- [ ] Add react router
- [ ] Write tests
- [ ] Storybook
